name: Craig Varjabedian Photography
favicon: null
layout_spectrum: 0.41485967324115336
typography_spectrum: 0.9260659685824066
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9352787500247359
  lightness: 0.4874127027578652
  saturation: 0.7311042749788612
  rhythmicContrast: 0.4231446429621428
purpose: []
